<?php
/**
 * Public unauthenticated testSSL report page.
 * URL: /report/<hash>/
 * $_params['route'] holds the hash.
 */

$hash = $_params['route'] ?? '';

if (!preg_match('/^[a-f0-9]{64}$/', $hash)) {
    http_response_code(404);
    include(dirname(__FILE__) . '/../error/404.php');
    return;
}

$TestSSL = new TestSSL($Database);
$scan    = $TestSSL->get_by_hash($hash);

if (!$scan) {
    http_response_code(404);
    include(dirname(__FILE__) . '/../error/404.php');
    return;
}

$rating_class = $TestSSL->rating_class($scan->rating ?? null);
$sections     = $scan->status === 'Completed' ? $TestSSL->parse_result($scan->json_result) : [];

$flask_icon = '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon-tabler icons-tabler-outline icon-tabler-flask"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M9 3l6 0" /><path d="M10 9l4 0" /><path d="M10 3v6l-4 11a.7 .7 0 0 0 .5 1h11a.7 .7 0 0 0 .5 -1l-4 -11v-6" /></svg>';
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>testSSL Report — <?php print htmlspecialchars($scan->hostname ?? ''); ?></title>
<link rel="stylesheet" href="/css/tabler.min.css">
<link rel="stylesheet" href="/css/tabler-icons.min.css">
<style>
  body { background: var(--tblr-body-bg); }
  .report-header { background: var(--tblr-bg-surface); border-bottom: 1px solid var(--tblr-border-color); padding: 1rem 0; margin-bottom: 2rem; }
</style>
</head>
<body class="antialiased">

<div class="report-header">
<div class="container">
  <div class="d-flex align-items-center gap-3">
    <?php print $flask_icon; ?>
    <div>
      <h1 class="h3 mb-0"><?php print _("testSSL Report"); ?></h1>
      <div class="text-muted small"><?php print htmlspecialchars($scan->tenant_name ?? ''); ?></div>
    </div>
    <?php if ($scan->rating): ?>
    <span class="badge badge-outline text-<?php print $rating_class; ?> fs-3 ms-auto px-3"><?php print htmlspecialchars($scan->rating); ?></span>
    <?php endif; ?>
  </div>
</div>
</div>

<div class="container">

<?php if ($scan->status === 'Completed'): ?>
<div style="margin-bottom:12px">
    <a href="/route/ajax/testssl-export-public.php?hash=<?php print htmlspecialchars($scan->hash); ?>&format=json" class="btn btn-sm bg-secondary-lt"><?php print _("Download JSON"); ?></a>
    <a href="/route/ajax/testssl-export-public.php?hash=<?php print htmlspecialchars($scan->hash); ?>&format=csv"  class="btn btn-sm bg-secondary-lt ms-1"><?php print _("Download CSV"); ?></a>
</div>
<?php endif; ?>

<?php include(dirname(__FILE__) . '/../testssl/report-body.php'); ?>

<div class="text-muted small text-center mt-4 mb-4">
    <?php print _("Generated by"); ?> php-ssl &mdash; <?php print htmlspecialchars($scan->tenant_name ?? ''); ?>
</div>

</div>

<script src="/js/jquery-3.6.0.min.js"></script>
<script src="/js/tabler.min.js"></script>
</body>
</html>
